### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by rylanharper** [vlbn/help#1]
Not an issue, but thank you for this it was a huge help with a client project I have going on! I was having trouble wrapping my head around how to use gsap with locomotive in Vue and this perfect 😄

**Comment by vlbn** [comment]
> Not an issue, but thank you for this it was a huge help with a client project I have going on! I was having trouble wrapping my head around how to use gsap with locomotive in Vue and this perfect 😄

i feel very happy this helped you, cheers!

**Comment by vlbn** [comment]
@rylanharper how did it go?
